addpath('C:/Users/nikol/OneDrive/Рабочий стол/labMatStat/MatStat/Lab9-10/octave/')
run('data.m')
run('data_regr.m')
run('data_regr_reduce.m')
run('regr_reduce_residuals.m')
run('regr_residuals.m')
run('mode_freq.m')
run('omegas.m')
run('inform_set.m')
run('corridor_of_joint_dep')
